# Task-1 : Arrays



You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

In [1]:
import numpy

def arrays(arr):
    a = numpy.array(arr, float)
    a = numpy.flip(a)
    return a

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Task-2 : Shape and Reshape

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

In [2]:
import numpy

array = list(map(int,input().split()))

arr = numpy.array(array)

new_arr = numpy.reshape(array,(3,3))
print(new_arr)


1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Task-3 :Transpose and Flatten 

You are given a NXM integer array matrix with space separated elements (N = rows and M = columns).
Your task is to print the transpose and flatten results.

In [3]:
import numpy

n,m = map(int,input().split())
array = []
for i in range(n):
    arr = input().split()
    array.append(arr)

array1 = numpy.array(array, int)


print(numpy.transpose(array1)) # Transpose of array1

print(array1.flatten()) # Array1 converted into 1D array


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Task-4 : Concatenate

You are given two integer arrays of size NxP and MxP ( N & M  are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

In [4]:
import numpy

# n and m are no. of rows for both array and p is column.

n, m, p = map(int,input().split()) 

lst1 = []
for i in range(n):
    a = input().split()
    lst1.append(a)
    
arr1 = numpy.array(lst1,int)

lst2 = []
for i in range(m):
    b = input().split()
    lst2.append(b)
    
arr2 = numpy.array(lst2,int)

print(numpy.concatenate((arr1,arr2),axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Task-5 : Zeros and Ones

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

In [5]:
import numpy

# parm consist 3 values, row, column and dimension of array
parm = list(map(int,input().split())) 

print(numpy.zeros((parm),dtype = int)) # Gives array of zero values
print(numpy.ones((parm), dtype = int)) # Gives array of one values


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Task-6 : Eye and Identity

Your task is to print an array of size N x M with its main diagonal elements as 0's and 1's everywhere else.

In [6]:
import numpy

numpy.set_printoptions(legacy='1.13')

n, m = map(int,input().split())

print(numpy.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Task-7 : Array Mathematics

You are given two integer arrays,A  and B of dimensions N x M.
Your task is to perform the following operations:

1. Add ( A+B )
2. Subtract ( A-B )
3. Multiply ( A*B )
4. Integer Division ( A/B )
5. Mod ( A%B )
6. Power ( A**B )

In [7]:
import numpy

n,m = map(int,input().split())
lst = []
for i in range(n):
    lst1 = list(map(int,input().split()))
    lst.append(lst1)
A = numpy.array(lst,int)

lst2 = []
for i in range(n):
    lst3 = list(map(int,input().split()))
    lst2.append(lst3)
B = numpy.array(lst2,int)
# Addition
add = A + B
print(add)

#Substraction
subs = A - B
print(subs)

# Multipication
multi = A*B
print(multi)

#Integer division
div = A//B
print(div)

# Mod
mod = A % B
print(mod)

# Power
power = A**B
print(power)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Task-8 : Floor, Ceil and Rint


You are given a 1-D array,A . Your task is to print the floor, ceil and rint  of all the elements of .

In [8]:
import numpy

# It helps to get output in same order
numpy.set_printoptions(legacy='1.13')

A = numpy.array((list(map(float,input().split()))))

# floor function gives the least integer value to given number.
print(numpy.floor(A))

# ceil function gives the value of greatest nearer integer.
print(numpy.ceil(A))

# rint function round of the value to its nearest integer.
print(numpy.rint(A))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Task-9 : Sum and Prod

You are given a 2-D array with dimensions N x M.
Your task is to perform the sum tool over axis 0 and then find the product of that result.

In [9]:
import numpy

n,m = map(int,input().split())

lst = []

for i in range(n):
    a = list(map(int,input().split()))
    lst.append(a)
    
A = numpy.array(lst)

sums = numpy.sum(A, axis=0)

print(numpy.prod(sums))


2 2
1 2
3 4
24


# Task-10 : 

You are given a 2-D array with dimensions N x M.
Your task is to perform the min function over axis 1 and then find the max of that.

In [10]:
import numpy

n,m = map(int,input().split())

lst = []

for i in range(n):
    a = list(map(int,input().split()))
    lst.append(a)
    
A = numpy.array(lst)

minimum = numpy.min(A,axis=1)

print(numpy.max(minimum))



4 2
2 5
3 7
1 3
4 0
3


# Task-11 : Mean, Var, and Std



You are given a 2-D array of size N x M.
Your task is to find:

1. The mean along axis 1.
2. The var along axis 0. 
3. The std along axis None.

In [11]:
import numpy

n,m = map(int,input().split())

lst = []
for i in range(n):
    a = list(map(int,input().split()))
    lst.append(a)
    
A = numpy.array(lst,float)

print(numpy.mean(A,axis=1))
print(numpy.var(A,axis=0))
print(round(numpy.std(A),11))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Task-12 : Dot and Cross



You are given two arrays A and B. Both have dimensions of N x N.
Your task is to compute their matrix product.

In [12]:
import numpy

n = int(input())

lst = []

for i in range(n):
    a = list(map(int,input().split()))
    lst.append(a)

A = numpy.array(lst)

lst1 = []
for i in range(n):
    a = list(map(int,input().split()))
    lst1.append(a)
    
B = numpy.array(lst1)

print(numpy.dot(A,B))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Task-13 : Inner and Outer



You are given two arrays: A and B.
Your task is to compute their inner and outer product.

In [13]:
import numpy

A = numpy.array(list(map(int,input().split())))
B = numpy.array(list(map(int,input().split())))

print(numpy.inner(A,B)) # The inner tool returns the inner product of two arrays.
print(numpy.outer(A,B)) # The outer tool returns the outer product of two arrays.



0 1
1 2
2
[[0 0]
 [1 2]]


# Task-14 : Polynomials

You are given the coefficients of a polynomial P.
Your task is to find the value of P at point x.

In [14]:
import numpy

# Value of coefficient
p = list(map(float,input().split()))

# Specific value
x = int(input())

print(numpy.polyval(p,x))

1.1 2 3
0
3.0


# Task-15 : Linear Algebra



You are given a square matrix A with dimensions N x N. Your task is to find the determinant. Note: Round the answer to 2 places after the decimal.

In [15]:
import numpy

n = int(input()) # Number of dimension of array

lst = [] # Empty list

for i in range(n):
    a = list(map(float,input().split()))
    lst.append(a)

# Array A    
A = numpy.array(lst)

print(round((numpy.linalg.det(A)),2)) # Determinent of array A.


2
1.1 1.1
1.1 1.1
0.0
